# Generated by Django 3.1.4 on 2021-01-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210102_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListUser',
        ),
    ]
